/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sqlprogramacion;

import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dfernandezrivas
 */
public class Interfad extends javax.swing.JFrame {

    /**
     * Creates new form Interfad
     */
    public static Object[] fila = new Object[5];

    public Interfad() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        apellidoLabel = new javax.swing.JLabel();
        Campo1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Campo2 = new javax.swing.JTextField();
        Botonborrar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        Campo3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Campo4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Campo5 = new javax.swing.JTextField();
        botonAñadir = new javax.swing.JButton();
        tabla = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier 10 Pitch", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tabla de Cartas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 380, 60));

        nombreLabel.setText("Id");
        jPanel1.add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        apellidoLabel.setText("Nombre");
        jPanel1.add(apellidoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        Campo1.setText("Id");
        Campo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo1ActionPerformed(evt);
            }
        });
        jPanel1.add(Campo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 160, -1));

        jLabel2.setText("Vida");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jButton1.setText("Mostrar todas las Cartas");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 110, -1));

        Campo2.setText("Apellidos del Alumno");
        jPanel1.add(Campo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 160, -1));

        Botonborrar.setBackground(new java.awt.Color(204, 0, 0));
        Botonborrar.setText("Borrar de la tabla");
        Botonborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonborrarActionPerformed(evt);
            }
        });
        jPanel1.add(Botonborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        botonSalir.setBackground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 84, -1));

        Campo3.setText("Vida");
        jPanel1.add(Campo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 160, -1));

        jLabel3.setText("Ataque ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        Campo4.setText("Ataque");
        jPanel1.add(Campo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 50, -1));

        jLabel4.setText("Coste");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        Campo5.setText("Coste");
        jPanel1.add(Campo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 50, -1));

        botonAñadir.setBackground(new java.awt.Color(51, 153, 0));
        botonAñadir.setText("Agregar a la tabla");
        botonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(botonAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 164, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Vida", "Ataque", "Coste"
            }
        ));
        tabla.setViewportView(jTable1);

        jPanel1.add(tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 197, 890, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirActionPerformed

        Connection conn = Metodos.conectar();
        Metodos metodos = new Metodos();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        fila[0] = Campo1.getText();
        fila[1] = Campo2.getText();
        fila[2] = Campo3.getText();
        fila[3] = Campo4.getText();
        fila[4] = Campo5.getText();
        modelo.addRow(fila);
        jTable1.setModel(modelo);
        //pruevas para insertar los datos directamente a las filas 
//        metodos.insertar(new Carta(fila[0], fila[1], fila[2], fila[3]), fila[4]);

    }//GEN-LAST:event_botonAñadirActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        Object[] posivilidades = {"Aceptar", "Cancelar"};
        int elegir = JOptionPane.showOptionDialog(rootPane, "¿En realidad desea realizar cerrar la aplicacion?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, posivilidades, "Aceptar");
        if (elegir == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
        }
    }//GEN-LAST:event_botonSalirActionPerformed

    private void BotonborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonborrarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.removeRow(0);
    }//GEN-LAST:event_BotonborrarActionPerformed

    private void Campo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfad().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botonborrar;
    private javax.swing.JTextField Campo1;
    private javax.swing.JTextField Campo2;
    private javax.swing.JTextField Campo3;
    private javax.swing.JTextField Campo4;
    private javax.swing.JTextField Campo5;
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JButton botonAñadir;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JScrollPane tabla;
    // End of variables declaration//GEN-END:variables
}
